In [6]:
import pickle
import random
import heapq
from collections import deque
from pathlib import Path
import pandas as pd
import streamlit.core.game_logic as game_logic
import pyarrow as pa

In [2]:
print("PyArrow version: ", pa.__version__)

PyArrow version:  23.0.1

In [3]:
pd.read_parquet('../data/final_movies.parquet')

,tconst,personIds,originalTitle,startYear,box_office,adjusted_box_office
0,tt0035423,"nm0043662,nm0118806,nm0126148,nm0179296,nm0294...",Kate & Leopold,2001.0,76019048,1.374809e+08
1,tt0036606,"nm0028791,nm0336942,nm0426834,nm0485392,nm0517...","Another Time, Another Place",1983.0,0,0.000000e+00
2,tt0042423,"nm0120684,nm0305239,nm0340563,nm0365092,nm0367...",The Dungeon of Harrow,1964.0,0,0.000000e+00
3,tt0044932,"nm1214148,nm2088491,nm5648446,nm7784675",Out of the Shadow,1961.0,0,0.000000e+00
4,tt0049079,"nm0579230,nm0897763",Una cita de amor,1958.0,0,0.000000e+00
...,...,...,...,...,...,...
83152,tt9908448,"nm10547143,nm3133401,nm3483889",The Bells of Hell,2018.0,0,0.000000e+00
83153,tt9908636,"nm10319155,nm10319156,nm10319158,nm10319161,nm...",Das Spiel der Hoffnung,2017.0,0,0.000000e+00
83154,tt9911046,"nm10536355,nm10536356,nm10536357,nm10536358,nm...",The Saving,2020.0,0,0.000000e+00
83155,tt9913660,"nm10175558,nm10209518,nm1067844,nm11900816,nm1...",No Apology,2019.0,0,0.000000e+00
83156,tt9916190,"nm10385419,nm10430118,nm10676018,nm11045562,nm...",Safeguard,2020.0,0,0.000000e+00

In [ ]:
pd.read_parquet('../data/actor_names.parquet')

,nconst,primaryName,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,"actor,miscellaneous,producer","tt0072308,tt0050419,tt0027125,tt0025164"
1,nm0000002,Lauren Bacall,"actress,miscellaneous,soundtrack","tt0037382,tt0075213,tt0038355,tt0117057"
2,nm0000003,Brigitte Bardot,"actress,music_department,producer","tt0057345,tt0049189,tt0056404,tt0054452"
3,nm0000004,John Belushi,"actor,writer,music_department","tt0072562,tt0077975,tt0080455,tt0078723"
4,nm0000005,Ingmar Bergman,"writer,director,actor","tt0050986,tt0069467,tt0050976,tt0083922"
...,...,...,...,...
2204110,nm9993663,Max Thursam,"actor,miscellaneous","tt8606950,tt10709768"
2204111,nm9993680,Christopher-Lawson Palmer,actor,"tt8295580,tt21745568,tt10427366,tt21047844"
2204112,nm9993693,Apsara Rani,"actress,archive_footage","tt12856788,tt39440956,tt13847502,tt8302382"
2204113,nm9993694,Chinmay Mishra,"actor,director,producer","tt18361688,tt18687502,tt8737752,tt9083282"
2204114,nm9993703,James Craigmyle,actor,"tt11212278,tt6914160,tt6225166,tt10627062"

In [2]:
pd.read_parquet('../data/revised-data/final_movies.parquet')

,movie_id,original_title,actors,year,revenue,adjusted_revenue
0,5,Four Rooms,"3131,3136,62,3141,3127,3129",1995,4257354.0,8.876780e+06
1,6,Judgment Night,"9777,2880",1993,12136938.0,2.679509e+07
2,11,Star Wars,"3,12248,4,2",1977,775398007.0,4.270401e+09
3,12,Finding Nemo,"5293,118,8783,19,13",2003,940335536.0,1.636219e+09
4,13,Forrest Gump,"31,35,6856,32,9640,33,21457",1994,677387716.0,1.454756e+09
...,...,...,...,...,...,...
16644,1641285,Reflections on 'the Little Dragon',"19429,51576",2001,0.0,0.000000e+00
16645,1641541,PaleyLive: It’s Always Sunny in Philadelphia 2...,"518,95101",2025,0.0,0.000000e+00
16646,1643508,Janet Jackson: Japanese Singles Collection - G...,"16866,938",2022,0.0,0.000000e+00
16650,1644700,Fats Waller Was Born Here,"70851,2047",2008,0.0,0.000000e+00
16651,1645833,Pulp Fiction: Behind The Scenes Montages,"2231,62,139,8891",2002,0.0,0.000000e+00

In [3]:
pd.read_parquet('../data/revised-data/actor_list.parquet')

                  name  tmdb_id
0       Robert De Niro      380
1       Jack Nicholson      514
2        Marlon Brando     3084
3    Denzel Washington     5292
4         Meryl Streep     5064
..                 ...      ...
995         Ned Beatty    13726
996        John Cleese     8930
997      John Turturro     1241
998        Jerry Lewis     3663
999        Paul Mescal  2326151

[1000 rows x 2 columns]

In [6]:
actors = pd.read_parquet('../data/revised-data/actor_list.parquet')
movies = pd.read_parquet('../data/revised-data/final_movies.parquet')

In [5]:
movie_actor_ids = set()
for actors_str in movies["actors"].head(10):
    for aid in str(actors_str).split(","):
        movie_actor_ids.add(aid.strip())

print("IDs from movies parquet:", list(movie_actor_ids)[:5])
print("IDs from actors parquet:", actors["tmdb_id"].head(5).tolist())

IDs from movies parquet: ['21457', '3131', '13', '33', '516']
IDs from actors parquet: [380, 514, 3084, 5292, 5064]

In [2]:
game_logic.build_and_save('../data/revised-data/final_movies.parquet', '../data/revised-data/actor_list.parquet', '../data/revised-data/game_data.pkl')

[build_and_save] Saved 6276 movies and 964 actors → ../data/revised-data/game_data.pkl

{'movies': {5: {'title': 'Four Rooms (1995)',
   'box_office': 8876779.74,
   'actor_ids': ['3131', '3136', '62', '3141', '3127', '3129']},
  6: {'title': 'Judgment Night (1993)',
   'box_office': 26795085.88,
   'actor_ids': ['9777', '2880']},
  11: {'title': 'Star Wars (1977)',
   'box_office': 4270400995.59,
   'actor_ids': ['3', '12248', '4', '2']},
  12: {'title': 'Finding Nemo (2003)',
   'box_office': 1636219349.52,
   'actor_ids': ['5293', '118', '8783', '19', '13']},
  13: {'title': 'Forrest Gump (1994)',
   'box_office': 1454756217.45,
   'actor_ids': ['31', '35', '6856', '32', '9640', '33', '21457']},
  14: {'title': 'American Beauty (1999)',
   'box_office': 676325222.11,
   'actor_ids': ['516', '2955', '2155', '1979', '19']},
  16: {'title': 'Dancer in the Dark (2000)',
   'box_office': 74262128.44,
   'actor_ids': ['50', '47', '1640']},
  17: {'title': 'The Dark (2005)',
   'box_office': 11027605.36,
   'actor_ids': ['49', '48']},
  20: {'title': 'My Life Without Me (2003)',
   'box_office': 21402464.58,
   'actor_ids': ['103', '98', '658']},
  22: {'title': 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)',
   'box_office': 1139744269.82,
   'actor_ids': ['85', '118', '116', '8691', '114', '378', '1709']},
  24: {'title': 'Kill Bill: Vol. 1 (2003)',
   'box_office': 314783405.14,
   'actor_ids': ['140', '139', '589']},
  25: {'title': 'Jarhead (2005)',
   'box_office': 162357574.51,
   'actor_ids': ['131', '134', '2955', '133', '17697']},
  28: {'title': 'Apocalypse Now (1979)',
   'box_office': 700533026.54,
   'actor_ids': ['3084', '3', '3087', '2975', '2778', '8349']},
  33: {'title': 'Unforgiven (1992)',
   'box_office': 362972151.39,
   'actor_ids': ['192', '193', '190', '194']},
  35: {'title': 'The Simpsons Movie (2007)',
   'box_office': 840674459.58,
   'actor_ids': ['31', '13']},
  38: {'title': 'Eternal Sunshine of the Spotless Mind (2004)',
   'box_office': 123508711.65,
   'actor_ids': ['204', '206', '205', '103', '207', '109']},
  58: {'title': "Pirates of the Caribbean: Dead Man's Chest (2006)",
   'box_office': 1739668760.13,
   'actor_ids': ['85', '116', '114', '1640', '378', '1709']},
  59: {'title': 'A History of Violence (2005)',
   'box_office': 102820165.42,
   'actor_ids': ['110', '228', '227', '49']},
  63: {'title': 'Twelve Monkeys (1995)',
   'box_office': 352042240.99,
   'actor_ids': ['287', '62', '290']},
  65: {'title': '8 Mile (2002)',
   'box_office': 428528374.55,
   'actor_ids': ['326', '335', '53650']},
  66: {'title': 'Absolute Power (1997)',
   'box_office': 99330587.97,
   'actor_ids': ['193', '190', '228', '350', '351', '28633']},
  68: {'title': 'Brazil (1985)',
   'box_office': 30624967.69,
   'actor_ids': ['380', '388', '382', '378', '65']},
  69: {'title': 'Walk the Line (2005)',
   'box_office': 312418593.99,
   'actor_ids': ['73421', '368', '417']},
  70: {'title': 'Million Dollar Baby (2004)',
   'box_office': 370507791.06,
   'actor_ids': ['192', '190', '448', '449', '53650']},
  71: {'title': 'Billy Elliot (2000)',
   'box_office': 202574921.56,
   'actor_ids': ['477', '478']},
  73: {'title': 'American History X (1998)',
   'box_office': 46319893.01,
   'actor_ids': ['826', '819']},
  74: {'title': 'War of the Worlds (2005)',
   'box_office': 1009963548.12,
   'actor_ids': ['192', '500', '504', '501', '38673', '39388']},
  75: {'title': 'Mars Attacks! (1996)',
   'box_office': 205806477.98,
   'actor_ids': ['514',
    '515',
    '524',
    '516',
    '522',
    '521',
    '2230',
    '520',
    '18979',
    '518',
    '70851',
    '517']},
  76: {'title': 'Before Sunrise (1995)',
   'box_office': 12483976.37,
   'actor_ids': ['569', '1146']},
  77: {'title': 'Memento (2000)',
   'box_office': 74260191.3,
   'actor_ids': ['529', '530']},
  78: {'title': 'Blade Runner (1982)',
   'box_office': 146206682.23,
   'actor_ids': ['3', '589', '587', '585']},
  80: {'title': 'Before Sunset (2004)',
   'box_office': 27335711.34,
   'actor_ids': ['569', '1146']},
  82: {'title': 'Miami Vice (2006)',
   'box_office': 267269889.26,
   'actor_ids': ['72466', '134', '16861']},
  85: {'title': 'Raiders of the Lost Ark (1981)',
   'box_office': 1467520354.06,
   'actor_ids': ['3', '655', '658']},
  87: {'title': 'Indiana Jones and the Temple of Doom (1984)',
   'box_office': 1068610125.45,
   'actor_ids': ['3', '707']},
  89: {'title': 'Indiana Jones and the Last Crusade (1989)',
   'box_office': 1235166808.05,
   'actor_ids': ['3', '738', '655', '741']},
  93: {'title': 'Anatomy of a Murder (1959)',
   'box_office': 88968452.43,
   'actor_ids': ['854', '862']},
  95: {'title': 'Armageddon (1998)',
   'box_office': 1073302788.48,
   'actor_ids': ['10017', '62', '882', '880', '887', '879', '884', '61981']},
  96: {'title': 'Beverly Hills Cop II (1987)',
   'box_office': 852466478.79,
   'actor_ids': ['2632', '923', '776']},
  98: {'title': 'Gladiator (2000)',
   'box_office': 862936406.23,
   'actor_ids': ['73421', '934', '194', '938']},
  103: {'title': 'Taxi Driver (1976)',
   'box_office': 167314636.79,
   'actor_ids': ['380', '1038', '1037', '13']},
  105: {'title': 'Back to the Future (1985)',
   'box_office': 1172575501.42,
   'actor_ids': ['521', '1062', '1954']},
  107: {'title': 'Snatch (2000)',
   'box_office': 154892831.53,
   'actor_ids': ['287', '1121', '976']},
  111: {'title': 'Scarface (1983)',
   'box_office': 222465038.38,
   'actor_ids': ['1158', '1160', '1164']},
  114: {'title': 'Pretty Woman (1990)',
   'box_office': 1149641651.14,
   'actor_ids': ['1204', '1205']},
  115: {'title': 'The Big Lebowski (1998)',
   'box_office': 91109640.33,
   'actor_ids': ['1231',
    '1229',
    '1233',
    '11207',
    '884',
    '1230',
    '16431',
    '1241']},
  116: {'title': 'Match Point (2005)',
   'box_office': 143228632.22,
   'actor_ids': ['1245', '1248', '1244']},
  117: {'title': 'The Untouchables (1987)',
   'box_office': 216751946.24,
   'actor_ids': ['380', '738', '1269', '1276', '1271']},
  118: {'title': 'Charlie and the Chocolate Factory (2005)',
   'box_office': 794426296.29,
   'actor_ids': ['85', '113', '1283', '1285', '1281']},
  120: {'title': 'The Lord of the Rings: The Fellowship of the Ring (2001)',
   'box_office': 1574339440.06,
   'actor_ids': ['112',
    '1327',
    '110',
    '113',
    '882',
    '1333',
    '655',
    '1328',
    '1331',
    '114',
    '109',
    '48',
    '65']},
  121: {'title': 'The Lord of the Rings: The Two Towers (2002)',
   'box_office': 1634339913.15,
   'actor_ids': ['112',
    '1327',
    '110',
    '113',
    '882',
    '1372',
    '1333',
    '655',
    '1328',
    '1331',
    '114',
    '109',
    '48']},
  122: {'title': 'The Lord of the Rings: The Return of the King (2003)',
   'box_office': 1946909084.38,
   'actor_ids': ['112',
    '1327',
    '110',
    '882',
    '1372',
    '1333',
    '655',
    '1328',
    '1331',
    '114',
    '109',
    '48',
    '65']},
  134: {'title': 'O Brother, Where Art Thou? (2000)',
   'box_office': 133239941.68,
   'actor_ids': ['1461', '18686', '1230', '1241']},
  137: {'title': 'Groundhog Day (1993)',
   'box_office': 156989004.42,
   'actor_ids': ['1532', '335']},
  141: {'title': 'Donnie Darko (2001)',
   'box_office': 13550578.94,
   'actor_ids': ['69597', '723', '131', '1579', '19274', '1581', '20089']},
  142: {'title': 'Brokeback Mountain (2005)',
   'box_office': 297773990.8,
   'actor_ids': ['1810', '1813', '131', '1812', '51072', '1772', '1811']},
  150: {'title': '48 Hrs. (1982)',
   'box_office': 276376628.71,
   'actor_ids': ['1733', '776']},
  153: {'title': 'Lost in Translation (2003)',
   'box_office': 208324031.46,
   'actor_ids': ['1532', '1245', '1772', '1771']},
  155: {'title': 'The Dark Knight (2008)',
   'box_office': 1566246369.8,
   'actor_ids': ['192', '1810', '3895', '64', '3894', '1579', '6383', '2037']},
  157: {'title': 'Star Trek III: The Search for Spock (1984)',
   'box_office': 279186429.17,
   'actor_ids': ['1748', '1062']},
  161: {'title': "Ocean's Eleven (2001)",
   'box_office': 814330442.64,
   'actor_ids': ['19492',
    '1204',
    '1896',
    '287',
    '1461',
    '1892',
    '1893',
    '1271',
    '1897',
    '17052']},
  162: {'title': 'Edward Scissorhands (1990)',
   'box_office': 213412692.01,
   'actor_ids': ['85', '1920', '1902', '1903']},
  163: {'title': "Ocean's Twelve (2004)",
   'box_office': 620028239.89,
   'actor_ids': ['1204',
    '1896',
    '287',
    '1461',
    '62',
    '1892',
    '1922',
    '3926',
    '1925',
    '1893',
    '1271',
    '1897',
    '17052']},
  164: {'title': "Breakfast at Tiffany's (1961)",
   'box_office': 102955787.27,
   'actor_ids': ['1932', '1934', '1936', '33923']},
  165: {'title': 'Back to the Future Part II (1989)',
   'box_office': 864824468.86,
   'actor_ids': ['1951', '521', '1062', '109', '1954']},
  167: {'title': 'K-PAX (2001)',
   'box_office': 90906570.18,
   'actor_ids': ['1229', '1979', '84497']},
  169: {'title': 'Predator 2 (1990)',
   'box_office': 141706966.94,
   'actor_ids': ['2048', '2047', '2053']},
  170: {'title': '28 Days Later (2002)',
   'box_office': 146064861.0,
   'actor_ids': ['2039', '2037']},
  174: {'title': 'Star Trek VI: The Undiscovered Country (1991)',
   'box_office': 229139284.92,
   'actor_ids': ['290', '1748']},
  176: {'title': 'Saw (2004)',
   'box_office': 177842346.52,
   'actor_ids': ['2047', '2130']},
  177: {'title': 'The Fisher King (1991)',
   'box_office': 99081456.57,
   'actor_ids': ['1229', '2157', '2167']},
  178: {'title': 'Blown Away (1994)',
   'box_office': 64762956.82,
   'actor_ids': ['2178', '1229', '2176', '9777']},
  179: {'title': 'The Interpreter (2005)',
   'box_office': 272521540.38,
   'actor_ids': ['2227', '2228', '2229']},
  180: {'title': 'Minority Report (2002)',
   'box_office': 632312581.12,
   'actor_ids': ['500', '72466', '6941', '2201', '2206']},
  182: {'title': 'The Good German (2006)',
   'box_office': 9651262.55,
   'actor_ids': ['112', '1461', '79087', '2219']},
  184: {'title': 'Jackie Brown (1997)',
   'box_office': 148158197.96,
   'actor_ids': ['380', '2231', '2230', '5694', '2232', '66']},
  186: {'title': 'Lucky Number Slevin (2006)',
   'box_office': 91863826.41,
   'actor_ids': ['192', '2282', '62', '140', '2283', '5694', '1004', '2299']},
  187: {'title': 'Sin City (2005)',
   'box_office': 265478569.93,
   'actor_ids': ['62',
    '1121',
    '56731',
    '5916',
    '2295',
    '2296',
    '61981',
    '109',
    '585',
    '2299']},
  189: {'title': 'Sin City: A Dame to Kill For (2014)',
   'box_office': 55642582.56,
   'actor_ids': ['62',
    '56731',
    '24045',
    '5916',
    '2295',
    '78324',
    '10912',
    '1062',
    '16851',
    '11477']},
  192: {'title': 'The Name of the Rose (1986)',
   'box_office': 228388748.15,
   'actor_ids': ['738', '1164']},
  193: {'title': 'Star Trek: Generations (1994)',
   'box_office': 253569261.94,
   'actor_ids': ['2395', '1748', '56890', '2387']},
  196: {'title': 'Back to the Future Part III (1990)',
   'box_office': 606636365.72,
   'actor_ids': ['2453', '1951', '521', '1062']},
  197: {'title': 'Braveheart (1995)',
   'box_office': 444565659.05,
   'actor_ids': ['2461', '1248', '2039', '1957']},
  199: {'title': 'Star Trek: First Contact (1996)',
   'box_office': 296470196.37,
   'actor_ids': ['2505', '2387']},
  200: {'title': 'Star Trek: Insurrection (1998)',
   'box_office': 218202856.59,
   'actor_ids': ['1164', '2387']},
  201: {'title': 'Star Trek: Nemesis (2002)',
   'box_office': 118808353.14,
   'actor_ids': ['2395', '2524', '2387']},
  203: {'title': 'Mean Streets (1973)',
   'box_office': 22100459.91,
   'actor_ids': ['380', '1037']},
  205: {'title': 'Hotel Rwanda (2004)',
   'box_office': 64952293.98,
   'actor_ids': ['1896', '73421', '1003', '1733', '2598']},
  207: {'title': 'Dead Poets Society (1989)',
   'box_office': 614390360.07,
   'actor_ids': ['2157', '569']},
  213: {'title': 'North by Northwest (1959)',
   'box_office': 147632025.76,
   'actor_ids': ['2638', '2091', '2641', '2639']},
  217: {'title': 'Indiana Jones and the Kingdom of the Crystal Skull (2008)',
   'box_office': 1226475013.37,
   'actor_ids': ['112', '3', '388', '10959', '5049', '5538']},
  218: {'title': 'The Terminator (1984)',
   'box_office': 251496269.86,
   'actor_ids': ['1100', '2713', '2714', '2053']},
  226: {'title': "Boys Don't Cry (1999)",
   'box_office': 21906477.84,
   'actor_ids': ['448', '2838', '133']},
  227: {'title': 'The Outsiders (1983)',
   'box_office': 113543931.31,
   'actor_ids': ['500', '2963', '2882', '723', '2876', '2879', '2880']},
  231: {'title': 'Syriana (2005)',
   'box_office': 157170335.39,
   'actor_ids': ['19492',
    '1461',
    '290',
    '1892',
    '227',
    '2955',
    '2956',
    '2954',
    '2983']},
  232: {'title': 'Rumble Fish (1983)',
   'box_office': 8405128.87,
   'actor_ids': ['2963', '2882', '2295', '2975', '2778', '2876']},
  235: {'title': 'Stand by Me (1986)',
   'box_office': 154724501.66,
   'actor_ids': ['3037', '3036', '2628', '741']},
  236: {'title': "Muriel's Wedding (1994)",
   'box_office': 32470900.08,
   'actor_ids': ['3051', '3052']},
  237: {'title': 'Young Adam (2003)',
   'box_office': 4350094.43,
   'actor_ids': ['3063', '3061']},
  238: {'title': 'The Godfather (1972)',
   'box_office': 1870353095.57,
   'actor_ids': ['3084', '1158', '3092', '3085', '3087', '3096', '3094']},
  239: {'title': 'Some Like It Hot (1959)',
   'box_office': 278026413.86,
   'actor_ids': ['3149', '3151']},
  240: {'title': 'The Godfather Part II (1974)',
   'box_office': 697909260.44,
   'actor_ids': ['380',
    '1158',
    '3092',
    '3085',
    '3087',
    '3096',
    '3094',
    '1004']},
  241: {'title': 'Natural Born Killers (1994)',
   'box_office': 107988858.05,
   'actor_ids': ['2176', '3223', '57755', '3196']},
  242: {'title': 'The Godfather Part III (1990)',
   'box_office': 339296147.24,
   'actor_ids': ['1158', '3092', '3094', '1271']},
  243: {'title': 'High Fidelity (2000)',
   'box_office': 87310174.26,
   'actor_ids': ['504', '1922', '3036', '3127', '70851']},
  245: {'title': 'About a Boy (2002)',
   'box_office': 227607380.6,
   'actor_ids': ['3051', '3293', '3291', '3292']},
  248: {'title': 'Pocketful of Miracles (1961)',
   'box_office': 54187256.46,
   'actor_ids': ['3380', '3383']},
  249: {'title': 'The War of the Roses (1989)',
   'box_office': 417274018.71,
   'actor_ids': ['3392', '3391', '1328', '518']},
  251: {'title': 'Ghost (1990)',
   'box_office': 1252829480.13,
   'actor_ids': ['3416', '2395', '723']},
  252: {'title': 'Willy Wonka & the Chocolate Factory (1971)',
   'box_office': 31443945.02,
   'actor_ids': ['3461', '3460']},
  254: {'title': 'King Kong (2005)',
   'box_office': 940539604.12,
   'actor_ids': ['3490', '3489', '1333', '70851', '478']},
  257: {'title': 'Oliver Twist (2005)',
   'box_office': 71214582.54,
   'actor_ids': ['2282', '2983']},
  261: {'title': 'Cat on a Hot Tin Roof (1958)',
   'box_office': 199308578.22,
   'actor_ids': ['3636', '3635', '2753']},
  262: {'title': 'The King of Comedy (1982)',
   'box_office': 8886831.36,
   'actor_ids': ['380', '66776', '3663']},
  268: {'title': 'Batman (1989)',
   'box_office': 1071519923.84,
   'actor_ids': ['514', '326', '3785', '2232']},
  272: {'title': 'Batman Begins (2005)',
   'box_office': 625871903.99,
   'actor_ids': ['192',
    '3895',
    '64',
    '3896',
    '3894',
    '3897',
    '207',
    '3899',
    '585',
    '2037']},
  274: {'title': 'The Silence of the Lambs (1991)',
   'box_office': 645028028.92,
   'actor_ids': ['1038', '4173']},
  275: {'title': 'Fargo (1996)',
   'box_office': 123056248.89,
   'actor_ids': ['3910', '884', '3905']},
  277: {'title': 'Underworld (2003)',
   'box_office': 166536330.13,
   'actor_ids': ['3967', '3968']},
  278: {'title': 'The Shawshank Redemption (1994)',
   'box_office': 60866070.15,
   'actor_ids': ['192', '504']},
  279: {'title': 'Amadeus (1984)',
   'box_office': 288837798.13,
   'actor_ids': ['1164', '3999']},
  280: {'title': 'Terminator 2: Judgment Day (1991)',
   'box_office': 1224529274.34,
   'actor_ids': ['1100', '2713']},
  281: {'title': 'Strange Days (1995)',
   'box_office': 16595489.38,
   'actor_ids': ['9780', '5469', '3196']},
  284: {'title': 'The Apartment (1960)',
   'box_office': 274458453.95,
   'actor_ids': ['3151', '4090']},
  285: {'title': "Pirates of the Caribbean: At World's End (2007)",
   'box_office': 1533896825.57,
   'actor_ids': ['85', '118', '116', '1619', '114', '1640', '378', '1709']},
  287: {'title': 'Bull Durham (1988)',
   'box_office': 138522894.61,
   'actor_ids': ['4038', '1269', '504']},
  290: {'title': 'Barton Fink (1991)',
   'box_office': 14553863.08,
   'actor_ids': ['3910', '351', '884', '3905', '4250', '1230', '1241']},
  293: {'title': 'A River Runs Through It (1992)',
   'box_office': 99069300.67,
   'actor_ids': ['287', '4135', '24045', '4154']},
  296: {'title': 'Terminator 3: Rise of the Machines (2003)',
   'box_office': 756916430.14,
   'actor_ids': ['1100', '6194']},
  297: {'title': 'Meet Joe Black (1998)',
   'box_office': 277028039.27,
   'actor_ids': ['4173', '287', '4726', '35515']},
  298: {'title': "Ocean's Thirteen (2007)",
   'box_office': 496543423.97,
   'actor_ids': ['1158',
    '1896',
    '287',
    '1461',
    '1892',
    '1925',
    '1893',
    '1271',
    '1897']},
  299: {'title': "Ocean's Eleven (1960)",
   'box_office': 30739346.84,
   'actor_ids': ['4090', '4347']},
  301: {'title': 'Rio Bravo (1959)',
   'box_office': 63946075.19,
   'actor_ids': ['4165', '4302']},
  308: {'title': 'Broken Flowers (2005)',
   'box_office': 78138919.21,
   'actor_ids': ['1532', '4431', '4430', '3063', '2838', '1146', '2954']},
  310: {'title': 'Bruce Almighty (2003)',
   'box_office': 843209904.04,
   'actor_ids': ['192', '206', '4491', '4495', '12134']},
  311: {'title': 'Once Upon a Time in America (1984)',
   'box_office': 17649716.79,
   'actor_ids': ['380', '4517', '6161', '4512', '1004']},
  313: {'title': 'Snow Cake (2006)',
   'box_office': 2254441.1,
   'actor_ids': ['10205', '530', '4566']},
  314: {'title': 'Catwoman (2004)',
   'box_office': 140335206.78,
   'actor_ids': ['4587', '4430', '4589']},
  318: {'title': 'The Million Dollar Hotel (2000)',
   'box_office': 196462.72,
   'actor_ids': ['2461', '63', '8535', '3129']},
  319: {'title': 'True Romance (1993)',
   'box_office': 27817401.89,
   'actor_ids': ['2231', '287', '4690', '64', '4687', '4691', '2778', '5576']},
  320: {'title': 'Insomnia (2002)',
   'box_office': 200638252.65,
   'actor_ids': ['1158', '2157', '448']},
  322: {'title': 'Mystic River (2003)',
   'box_office': 272837922.4,
   'actor_ids': ['504', '4724', '350', '2228', '4726', '2975', '4730']},
  326: {'title': 'Snakes on a Plane (2006)',
   'box_office': 101200346.85,
   'actor_ids': ['2231', '60900']},
  329: {'title': 'Jurassic Park (1993)',
   'box_office': 2031332657.29,
   'actor_ids': ['2231', '4785', '4784', '4786']},
  330: {'title': 'The Lost World: Jurassic Park (1997)',
   'box_office': 1226542425.34,
   'actor_ids': ['1231', '4785', '4935', '4937', '4786']},
  331: {'title': 'Jurassic Park III (2001)',
   'box_office': 666292461.76,
   'actor_ids': ['4784', '3905', '4939']},
  332: {'title': 'Inspector Gadget (1999)',
   'box_office': 255125124.18,
   'actor_ids': ['4756', '49961']},
  334: {'title': 'Magnolia (1999)',
   'box_office': 91971622.33,
   'actor_ids': ['1231',
    '500',
    '1233',
    '4765',
    '7427',
    '4764',
    '3905',
    '658']},
  339: {'title': 'Night on Earth (1991)',
   'box_office': 4767324.27,
   'actor_ids': ['1920', '4818', '4800', '12647']},
  345: {'title': 'Eyes Wide Shut (1999)',
   'box_office': 307699591.28,
   'actor_ids': ['112', '500', '2227']},
  348: {'title': 'Alien (1979)',
   'box_office': 490054614.23,
   'actor_ids': ['10205', '5049', '65']},
  350: {'title': 'The Devil Wears Prada (2006)',
   'box_office': 533081240.39,

In [ ]:
game_data = game_logic.load_data('data/revised-data/game_data.pkl')

In [12]:
game_data

{'movies': {5: {'title': 'Four Rooms (1995)',
   'box_office': 8876779.74,
   'actor_ids': ['3131', '3136', '62', '3141', '3127', '3129']},
  6: {'title': 'Judgment Night (1993)',
   'box_office': 26795085.88,
   'actor_ids': ['9777', '2880']},
  11: {'title': 'Star Wars (1977)',
   'box_office': 4270400995.59,
   'actor_ids': ['3', '12248', '4', '2']},
  12: {'title': 'Finding Nemo (2003)',
   'box_office': 1636219349.52,
   'actor_ids': ['5293', '118', '8783', '19', '13']},
  13: {'title': 'Forrest Gump (1994)',
   'box_office': 1454756217.45,
   'actor_ids': ['31', '35', '6856', '32', '9640', '33', '21457']},
  14: {'title': 'American Beauty (1999)',
   'box_office': 676325222.11,
   'actor_ids': ['516', '2955', '2155', '1979', '19']},
  16: {'title': 'Dancer in the Dark (2000)',
   'box_office': 74262128.44,
   'actor_ids': ['50', '47', '1640']},
  17: {'title': 'The Dark (2005)',
   'box_office': 11027605.36,
   'actor_ids': ['49', '48']},
  20: {'title': 'My Life Without Me (2003)',
   'box_office': 21402464.58,
   'actor_ids': ['103', '98', '658']},
  22: {'title': 'Pirates of the Caribbean: The Curse of the Black Pearl (2003)',
   'box_office': 1139744269.82,
   'actor_ids': ['85', '118', '116', '8691', '114', '378', '1709']},
  24: {'title': 'Kill Bill: Vol. 1 (2003)',
   'box_office': 314783405.14,
   'actor_ids': ['140', '139', '589']},
  25: {'title': 'Jarhead (2005)',
   'box_office': 162357574.51,
   'actor_ids': ['131', '134', '2955', '133', '17697']},
  28: {'title': 'Apocalypse Now (1979)',
   'box_office': 700533026.54,
   'actor_ids': ['3084', '3', '3087', '2975', '2778', '8349']},
  33: {'title': 'Unforgiven (1992)',
   'box_office': 362972151.39,
   'actor_ids': ['192', '193', '190', '194']},
  35: {'title': 'The Simpsons Movie (2007)',
   'box_office': 840674459.58,
   'actor_ids': ['31', '13']},
  38: {'title': 'Eternal Sunshine of the Spotless Mind (2004)',
   'box_office': 123508711.65,
   'actor_ids': ['204', '206', '205', '103', '207', '109']},
  58: {'title': "Pirates of the Caribbean: Dead Man's Chest (2006)",
   'box_office': 1739668760.13,
   'actor_ids': ['85', '116', '114', '1640', '378', '1709']},
  59: {'title': 'A History of Violence (2005)',
   'box_office': 102820165.42,
   'actor_ids': ['110', '228', '227', '49']},
  63: {'title': 'Twelve Monkeys (1995)',
   'box_office': 352042240.99,
   'actor_ids': ['287', '62', '290']},
  65: {'title': '8 Mile (2002)',
   'box_office': 428528374.55,
   'actor_ids': ['326', '335', '53650']},
  66: {'title': 'Absolute Power (1997)',
   'box_office': 99330587.97,
   'actor_ids': ['193', '190', '228', '350', '351', '28633']},
  68: {'title': 'Brazil (1985)',
   'box_office': 30624967.69,
   'actor_ids': ['380', '388', '382', '378', '65']},
  69: {'title': 'Walk the Line (2005)',
   'box_office': 312418593.99,
   'actor_ids': ['73421', '368', '417']},
  70: {'title': 'Million Dollar Baby (2004)',
   'box_office': 370507791.06,
   'actor_ids': ['192', '190', '448', '449', '53650']},
  71: {'title': 'Billy Elliot (2000)',
   'box_office': 202574921.56,
   'actor_ids': ['477', '478']},
  73: {'title': 'American History X (1998)',
   'box_office': 46319893.01,
   'actor_ids': ['826', '819']},
  74: {'title': 'War of the Worlds (2005)',
   'box_office': 1009963548.12,
   'actor_ids': ['192', '500', '504', '501', '38673', '39388']},
  75: {'title': 'Mars Attacks! (1996)',
   'box_office': 205806477.98,
   'actor_ids': ['514',
    '515',
    '524',
    '516',
    '522',
    '521',
    '2230',
    '520',
    '18979',
    '518',
    '70851',
    '517']},
  76: {'title': 'Before Sunrise (1995)',
   'box_office': 12483976.37,
   'actor_ids': ['569', '1146']},
  77: {'title': 'Memento (2000)',
   'box_office': 74260191.3,
   'actor_ids': ['529', '530']},
  78: {'title': 'Blade Runner (1982)',
   'box_office': 146206682.23,
   'actor_ids': ['3', '589', '587', '585']},
  80: {'title': 'Before Sunset (2004)',
   'box_office': 27335711.34,
   'actor_ids': ['569', '1146']},
  82: {'title': 'Miami Vice (2006)',
   'box_office': 267269889.26,
   'actor_ids': ['72466', '134', '16861']},
  85: {'title': 'Raiders of the Lost Ark (1981)',
   'box_office': 1467520354.06,
   'actor_ids': ['3', '655', '658']},
  87: {'title': 'Indiana Jones and the Temple of Doom (1984)',
   'box_office': 1068610125.45,
   'actor_ids': ['3', '707']},
  89: {'title': 'Indiana Jones and the Last Crusade (1989)',
   'box_office': 1235166808.05,
   'actor_ids': ['3', '738', '655', '741']},
  93: {'title': 'Anatomy of a Murder (1959)',
   'box_office': 88968452.43,
   'actor_ids': ['854', '862']},
  95: {'title': 'Armageddon (1998)',
   'box_office': 1073302788.48,
   'actor_ids': ['10017', '62', '882', '880', '887', '879', '884', '61981']},
  96: {'title': 'Beverly Hills Cop II (1987)',
   'box_office': 852466478.79,
   'actor_ids': ['2632', '923', '776']},
  98: {'title': 'Gladiator (2000)',
   'box_office': 862936406.23,
   'actor_ids': ['73421', '934', '194', '938']},
  103: {'title': 'Taxi Driver (1976)',
   'box_office': 167314636.79,
   'actor_ids': ['380', '1038', '1037', '13']},
  105: {'title': 'Back to the Future (1985)',
   'box_office': 1172575501.42,
   'actor_ids': ['521', '1062', '1954']},
  107: {'title': 'Snatch (2000)',
   'box_office': 154892831.53,
   'actor_ids': ['287', '1121', '976']},
  111: {'title': 'Scarface (1983)',
   'box_office': 222465038.38,
   'actor_ids': ['1158', '1160', '1164']},
  114: {'title': 'Pretty Woman (1990)',
   'box_office': 1149641651.14,
   'actor_ids': ['1204', '1205']},
  115: {'title': 'The Big Lebowski (1998)',
   'box_office': 91109640.33,
   'actor_ids': ['1231',
    '1229',
    '1233',
    '11207',
    '884',
    '1230',
    '16431',
    '1241']},
  116: {'title': 'Match Point (2005)',
   'box_office': 143228632.22,
   'actor_ids': ['1245', '1248', '1244']},
  117: {'title': 'The Untouchables (1987)',
   'box_office': 216751946.24,
   'actor_ids': ['380', '738', '1269', '1276', '1271']},
  118: {'title': 'Charlie and the Chocolate Factory (2005)',
   'box_office': 794426296.29,
   'actor_ids': ['85', '113', '1283', '1285', '1281']},
  120: {'title': 'The Lord of the Rings: The Fellowship of the Ring (2001)',
   'box_office': 1574339440.06,
   'actor_ids': ['112',
    '1327',
    '110',
    '113',
    '882',
    '1333',
    '655',
    '1328',
    '1331',
    '114',
    '109',
    '48',
    '65']},
  121: {'title': 'The Lord of the Rings: The Two Towers (2002)',
   'box_office': 1634339913.15,
   'actor_ids': ['112',
    '1327',
    '110',
    '113',
    '882',
    '1372',
    '1333',
    '655',
    '1328',
    '1331',
    '114',
    '109',
    '48']},
  122: {'title': 'The Lord of the Rings: The Return of the King (2003)',
   'box_office': 1946909084.38,
   'actor_ids': ['112',
    '1327',
    '110',
    '882',
    '1372',
    '1333',
    '655',
    '1328',
    '1331',
    '114',
    '109',
    '48',
    '65']},
  134: {'title': 'O Brother, Where Art Thou? (2000)',
   'box_office': 133239941.68,
   'actor_ids': ['1461', '18686', '1230', '1241']},
  137: {'title': 'Groundhog Day (1993)',
   'box_office': 156989004.42,
   'actor_ids': ['1532', '335']},
  141: {'title': 'Donnie Darko (2001)',
   'box_office': 13550578.94,
   'actor_ids': ['69597', '723', '131', '1579', '19274', '1581', '20089']},
  142: {'title': 'Brokeback Mountain (2005)',
   'box_office': 297773990.8,
   'actor_ids': ['1810', '1813', '131', '1812', '51072', '1772', '1811']},
  150: {'title': '48 Hrs. (1982)',
   'box_office': 276376628.71,
   'actor_ids': ['1733', '776']},
  153: {'title': 'Lost in Translation (2003)',
   'box_office': 208324031.46,
   'actor_ids': ['1532', '1245', '1772', '1771']},
  155: {'title': 'The Dark Knight (2008)',
   'box_office': 1566246369.8,
   'actor_ids': ['192', '1810', '3895', '64', '3894', '1579', '6383', '2037']},
  157: {'title': 'Star Trek III: The Search for Spock (1984)',
   'box_office': 279186429.17,
   'actor_ids': ['1748', '1062']},
  161: {'title': "Ocean's Eleven (2001)",
   'box_office': 814330442.64,
   'actor_ids': ['19492',
    '1204',
    '1896',
    '287',
    '1461',
    '1892',
    '1893',
    '1271',
    '1897',
    '17052']},
  162: {'title': 'Edward Scissorhands (1990)',
   'box_office': 213412692.01,
   'actor_ids': ['85', '1920', '1902', '1903']},
  163: {'title': "Ocean's Twelve (2004)",
   'box_office': 620028239.89,
   'actor_ids': ['1204',
    '1896',
    '287',
    '1461',
    '62',
    '1892',
    '1922',
    '3926',
    '1925',
    '1893',
    '1271',
    '1897',
    '17052']},
  164: {'title': "Breakfast at Tiffany's (1961)",
   'box_office': 102955787.27,
   'actor_ids': ['1932', '1934', '1936', '33923']},
  165: {'title': 'Back to the Future Part II (1989)',
   'box_office': 864824468.86,
   'actor_ids': ['1951', '521', '1062', '109', '1954']},
  167: {'title': 'K-PAX (2001)',
   'box_office': 90906570.18,
   'actor_ids': ['1229', '1979', '84497']},
  169: {'title': 'Predator 2 (1990)',
   'box_office': 141706966.94,
   'actor_ids': ['2048', '2047', '2053']},
  170: {'title': '28 Days Later (2002)',
   'box_office': 146064861.0,
   'actor_ids': ['2039', '2037']},
  174: {'title': 'Star Trek VI: The Undiscovered Country (1991)',
   'box_office': 229139284.92,
   'actor_ids': ['290', '1748']},
  176: {'title': 'Saw (2004)',
   'box_office': 177842346.52,
   'actor_ids': ['2047', '2130']},
  177: {'title': 'The Fisher King (1991)',
   'box_office': 99081456.57,
   'actor_ids': ['1229', '2157', '2167']},
  178: {'title': 'Blown Away (1994)',
   'box_office': 64762956.82,
   'actor_ids': ['2178', '1229', '2176', '9777']},
  179: {'title': 'The Interpreter (2005)',
   'box_office': 272521540.38,
   'actor_ids': ['2227', '2228', '2229']},
  180: {'title': 'Minority Report (2002)',
   'box_office': 632312581.12,
   'actor_ids': ['500', '72466', '6941', '2201', '2206']},
  182: {'title': 'The Good German (2006)',
   'box_office': 9651262.55,
   'actor_ids': ['112', '1461', '79087', '2219']},
  184: {'title': 'Jackie Brown (1997)',
   'box_office': 148158197.96,
   'actor_ids': ['380', '2231', '2230', '5694', '2232', '66']},
  186: {'title': 'Lucky Number Slevin (2006)',
   'box_office': 91863826.41,
   'actor_ids': ['192', '2282', '62', '140', '2283', '5694', '1004', '2299']},
  187: {'title': 'Sin City (2005)',
   'box_office': 265478569.93,
   'actor_ids': ['62',
    '1121',
    '56731',
    '5916',
    '2295',
    '2296',
    '61981',
    '109',
    '585',
    '2299']},
  189: {'title': 'Sin City: A Dame to Kill For (2014)',
   'box_office': 55642582.56,
   'actor_ids': ['62',
    '56731',
    '24045',
    '5916',
    '2295',
    '78324',
    '10912',
    '1062',
    '16851',
    '11477']},
  192: {'title': 'The Name of the Rose (1986)',
   'box_office': 228388748.15,
   'actor_ids': ['738', '1164']},
  193: {'title': 'Star Trek: Generations (1994)',
   'box_office': 253569261.94,
   'actor_ids': ['2395', '1748', '56890', '2387']},
  196: {'title': 'Back to the Future Part III (1990)',
   'box_office': 606636365.72,
   'actor_ids': ['2453', '1951', '521', '1062']},
  197: {'title': 'Braveheart (1995)',
   'box_office': 444565659.05,
   'actor_ids': ['2461', '1248', '2039', '1957']},
  199: {'title': 'Star Trek: First Contact (1996)',
   'box_office': 296470196.37,
   'actor_ids': ['2505', '2387']},
  200: {'title': 'Star Trek: Insurrection (1998)',
   'box_office': 218202856.59,
   'actor_ids': ['1164', '2387']},
  201: {'title': 'Star Trek: Nemesis (2002)',
   'box_office': 118808353.14,
   'actor_ids': ['2395', '2524', '2387']},
  203: {'title': 'Mean Streets (1973)',
   'box_office': 22100459.91,
   'actor_ids': ['380', '1037']},
  205: {'title': 'Hotel Rwanda (2004)',
   'box_office': 64952293.98,
   'actor_ids': ['1896', '73421', '1003', '1733', '2598']},
  207: {'title': 'Dead Poets Society (1989)',
   'box_office': 614390360.07,
   'actor_ids': ['2157', '569']},
  213: {'title': 'North by Northwest (1959)',
   'box_office': 147632025.76,
   'actor_ids': ['2638', '2091', '2641', '2639']},
  217: {'title': 'Indiana Jones and the Kingdom of the Crystal Skull (2008)',
   'box_office': 1226475013.37,
   'actor_ids': ['112', '3', '388', '10959', '5049', '5538']},
  218: {'title': 'The Terminator (1984)',
   'box_office': 251496269.86,
   'actor_ids': ['1100', '2713', '2714', '2053']},
  226: {'title': "Boys Don't Cry (1999)",
   'box_office': 21906477.84,
   'actor_ids': ['448', '2838', '133']},
  227: {'title': 'The Outsiders (1983)',
   'box_office': 113543931.31,
   'actor_ids': ['500', '2963', '2882', '723', '2876', '2879', '2880']},
  231: {'title': 'Syriana (2005)',
   'box_office': 157170335.39,
   'actor_ids': ['19492',
    '1461',
    '290',
    '1892',
    '227',
    '2955',
    '2956',
    '2954',
    '2983']},
  232: {'title': 'Rumble Fish (1983)',
   'box_office': 8405128.87,
   'actor_ids': ['2963', '2882', '2295', '2975', '2778', '2876']},
  235: {'title': 'Stand by Me (1986)',
   'box_office': 154724501.66,
   'actor_ids': ['3037', '3036', '2628', '741']},
  236: {'title': "Muriel's Wedding (1994)",
   'box_office': 32470900.08,
   'actor_ids': ['3051', '3052']},
  237: {'title': 'Young Adam (2003)',
   'box_office': 4350094.43,
   'actor_ids': ['3063', '3061']},
  238: {'title': 'The Godfather (1972)',
   'box_office': 1870353095.57,
   'actor_ids': ['3084', '1158', '3092', '3085', '3087', '3096', '3094']},
  239: {'title': 'Some Like It Hot (1959)',
   'box_office': 278026413.86,
   'actor_ids': ['3149', '3151']},
  240: {'title': 'The Godfather Part II (1974)',
   'box_office': 697909260.44,
   'actor_ids': ['380',
    '1158',
    '3092',
    '3085',
    '3087',
    '3096',
    '3094',
    '1004']},
  241: {'title': 'Natural Born Killers (1994)',
   'box_office': 107988858.05,
   'actor_ids': ['2176', '3223', '57755', '3196']},
  242: {'title': 'The Godfather Part III (1990)',
   'box_office': 339296147.24,
   'actor_ids': ['1158', '3092', '3094', '1271']},
  243: {'title': 'High Fidelity (2000)',
   'box_office': 87310174.26,
   'actor_ids': ['504', '1922', '3036', '3127', '70851']},
  245: {'title': 'About a Boy (2002)',
   'box_office': 227607380.6,
   'actor_ids': ['3051', '3293', '3291', '3292']},
  248: {'title': 'Pocketful of Miracles (1961)',
   'box_office': 54187256.46,
   'actor_ids': ['3380', '3383']},
  249: {'title': 'The War of the Roses (1989)',
   'box_office': 417274018.71,
   'actor_ids': ['3392', '3391', '1328', '518']},
  251: {'title': 'Ghost (1990)',
   'box_office': 1252829480.13,
   'actor_ids': ['3416', '2395', '723']},
  252: {'title': 'Willy Wonka & the Chocolate Factory (1971)',
   'box_office': 31443945.02,
   'actor_ids': ['3461', '3460']},
  254: {'title': 'King Kong (2005)',
   'box_office': 940539604.12,
   'actor_ids': ['3490', '3489', '1333', '70851', '478']},
  257: {'title': 'Oliver Twist (2005)',
   'box_office': 71214582.54,
   'actor_ids': ['2282', '2983']},
  261: {'title': 'Cat on a Hot Tin Roof (1958)',
   'box_office': 199308578.22,
   'actor_ids': ['3636', '3635', '2753']},
  262: {'title': 'The King of Comedy (1982)',
   'box_office': 8886831.36,
   'actor_ids': ['380', '66776', '3663']},
  268: {'title': 'Batman (1989)',
   'box_office': 1071519923.84,
   'actor_ids': ['514', '326', '3785', '2232']},
  272: {'title': 'Batman Begins (2005)',
   'box_office': 625871903.99,
   'actor_ids': ['192',
    '3895',
    '64',
    '3896',
    '3894',
    '3897',
    '207',
    '3899',
    '585',
    '2037']},
  274: {'title': 'The Silence of the Lambs (1991)',
   'box_office': 645028028.92,
   'actor_ids': ['1038', '4173']},
  275: {'title': 'Fargo (1996)',
   'box_office': 123056248.89,
   'actor_ids': ['3910', '884', '3905']},
  277: {'title': 'Underworld (2003)',
   'box_office': 166536330.13,
   'actor_ids': ['3967', '3968']},
  278: {'title': 'The Shawshank Redemption (1994)',
   'box_office': 60866070.15,
   'actor_ids': ['192', '504']},
  279: {'title': 'Amadeus (1984)',
   'box_office': 288837798.13,
   'actor_ids': ['1164', '3999']},
  280: {'title': 'Terminator 2: Judgment Day (1991)',
   'box_office': 1224529274.34,
   'actor_ids': ['1100', '2713']},
  281: {'title': 'Strange Days (1995)',
   'box_office': 16595489.38,
   'actor_ids': ['9780', '5469', '3196']},
  284: {'title': 'The Apartment (1960)',
   'box_office': 274458453.95,
   'actor_ids': ['3151', '4090']},
  285: {'title': "Pirates of the Caribbean: At World's End (2007)",
   'box_office': 1533896825.57,
   'actor_ids': ['85', '118', '116', '1619', '114', '1640', '378', '1709']},
  287: {'title': 'Bull Durham (1988)',
   'box_office': 138522894.61,
   'actor_ids': ['4038', '1269', '504']},
  290: {'title': 'Barton Fink (1991)',
   'box_office': 14553863.08,
   'actor_ids': ['3910', '351', '884', '3905', '4250', '1230', '1241']},
  293: {'title': 'A River Runs Through It (1992)',
   'box_office': 99069300.67,
   'actor_ids': ['287', '4135', '24045', '4154']},
  296: {'title': 'Terminator 3: Rise of the Machines (2003)',
   'box_office': 756916430.14,
   'actor_ids': ['1100', '6194']},
  297: {'title': 'Meet Joe Black (1998)',
   'box_office': 277028039.27,
   'actor_ids': ['4173', '287', '4726', '35515']},
  298: {'title': "Ocean's Thirteen (2007)",
   'box_office': 496543423.97,
   'actor_ids': ['1158',
    '1896',
    '287',
    '1461',
    '1892',
    '1925',
    '1893',
    '1271',
    '1897']},
  299: {'title': "Ocean's Eleven (1960)",
   'box_office': 30739346.84,
   'actor_ids': ['4090', '4347']},
  301: {'title': 'Rio Bravo (1959)',
   'box_office': 63946075.19,
   'actor_ids': ['4165', '4302']},
  308: {'title': 'Broken Flowers (2005)',
   'box_office': 78138919.21,
   'actor_ids': ['1532', '4431', '4430', '3063', '2838', '1146', '2954']},
  310: {'title': 'Bruce Almighty (2003)',
   'box_office': 843209904.04,
   'actor_ids': ['192', '206', '4491', '4495', '12134']},
  311: {'title': 'Once Upon a Time in America (1984)',
   'box_office': 17649716.79,
   'actor_ids': ['380', '4517', '6161', '4512', '1004']},
  313: {'title': 'Snow Cake (2006)',
   'box_office': 2254441.1,
   'actor_ids': ['10205', '530', '4566']},
  314: {'title': 'Catwoman (2004)',
   'box_office': 140335206.78,
   'actor_ids': ['4587', '4430', '4589']},
  318: {'title': 'The Million Dollar Hotel (2000)',
   'box_office': 196462.72,
   'actor_ids': ['2461', '63', '8535', '3129']},
  319: {'title': 'True Romance (1993)',
   'box_office': 27817401.89,
   'actor_ids': ['2231', '287', '4690', '64', '4687', '4691', '2778', '5576']},
  320: {'title': 'Insomnia (2002)',
   'box_office': 200638252.65,
   'actor_ids': ['1158', '2157', '448']},
  322: {'title': 'Mystic River (2003)',
   'box_office': 272837922.4,
   'actor_ids': ['504', '4724', '350', '2228', '4726', '2975', '4730']},
  326: {'title': 'Snakes on a Plane (2006)',
   'box_office': 101200346.85,
   'actor_ids': ['2231', '60900']},
  329: {'title': 'Jurassic Park (1993)',
   'box_office': 2031332657.29,
   'actor_ids': ['2231', '4785', '4784', '4786']},
  330: {'title': 'The Lost World: Jurassic Park (1997)',
   'box_office': 1226542425.34,
   'actor_ids': ['1231', '4785', '4935', '4937', '4786']},
  331: {'title': 'Jurassic Park III (2001)',
   'box_office': 666292461.76,
   'actor_ids': ['4784', '3905', '4939']},
  332: {'title': 'Inspector Gadget (1999)',
   'box_office': 255125124.18,
   'actor_ids': ['4756', '49961']},
  334: {'title': 'Magnolia (1999)',
   'box_office': 91971622.33,
   'actor_ids': ['1231',
    '500',
    '1233',
    '4765',
    '7427',
    '4764',
    '3905',
    '658']},
  339: {'title': 'Night on Earth (1991)',
   'box_office': 4767324.27,
   'actor_ids': ['1920', '4818', '4800', '12647']},
  345: {'title': 'Eyes Wide Shut (1999)',
   'box_office': 307699591.28,
   'actor_ids': ['112', '500', '2227']},
  348: {'title': 'Alien (1979)',
   'box_office': 490054614.23,
   'actor_ids': ['10205', '5049', '65']},
  350: {'title': 'The Devil Wears Prada (2006)',
   'box_office': 533081240.39,

In [4]:
game = game_logic.generate_game("box_office", game_data)
game

{'game_mode': 'box_office',
 'start_actor_id': '9066',
 'start_actor_name': 'Judy Garland',
 'target_actor_id': '52374',
 'target_actor_name': 'Bruce Davison',
 'optimal_path': {'total_box_office': 172036.16,
  'path': [('Liza: A Truly Terrific Absolutely True Story (2025)',
    'Mia Farrow'),
   ('Miami Rhapsody (1995)', 'Sarah Jessica Parker'),
   ('ShowBusiness: The Road to Broadway (2007)', 'Nathan Lane'),
   ('The Lion King 1½ (2004)', 'Whoopi Goldberg'),
   ('Pauly Shore Is Dead (2003)', 'Vince Vaughn'),
   ('A Case of You (2013)', 'Brendan Fraser'),
   ('...So Goes the Nation (2006)', 'Steve Buscemi'),
   ('Day of the Fight (2024)', 'Joe Pesci'),
   ('Short Eyes (1977)', 'Bruce Davison')],
  'is_successful': True},
 'is_valid': True}

In [7]:
actors[actors['name'] == 'Brad Pitt']

         name  tmdb_id
99  Brad Pitt      287

In [9]:
game_logic.get_movies_for_actor('287', game_data)

{63: 'Twelve Monkeys (1995)',
 107: 'Snatch (2000)',
 161: "Ocean's Eleven (2001)",
 163: "Ocean's Twelve (2004)",
 293: 'A River Runs Through It (1992)',
 297: 'Meet Joe Black (1998)',
 298: "Ocean's Thirteen (2007)",
 319: 'True Romance (1993)',
 492: 'Being John Malkovich (1999)',
 550: 'Fight Club (1999)',
 628: 'Interview with the Vampire (1994)',
 652: 'Troy (2004)',
 787: 'Mr. & Mrs. Smith (2005)',
 807: 'Se7en (1995)',
 819: 'Sleepers (1996)',
 978: 'Seven Years in Tibet (1997)',
 1164: 'Babel (2006)',
 1535: 'Spy Game (2001)',
 1541: 'Thelma & Louise (1991)',
 4476: 'Legends of the Fall (1994)',
 4477: "The Devil's Own (1997)",
 4512: 'The Assassination of Jesse James by the Coward Robert Ford (2007)',
 4912: 'Confessions of a Dangerous Mind (2002)',
 4922: 'The Curious Case of Benjamin Button (2008)',
 4944: 'Burn After Reading (2008)',
 6073: 'The Mexican (2001)',
 8967: 'The Tree of Life (2011)',
 10909: 'Kalifornia (1993)',
 13703: 'Less Than Zero (1987)',
 14239: 'Cool World (1992)',
 14411: 'Sinbad: Legend of the Seven Seas (2003)',
 15186: 'Full Frontal (2002)',
 16869: 'Inglourious Basterds (2009)',
 34379: "No Man's Land (1987)",
 38055: 'Megamind (2010)',
 39452: 'Exit Through the Gift Shop (2010)',
 45145: 'Johnny Suede (1991)',
 50463: 'The Favor (1994)',
 60308: 'Moneyball (2011)',
 64689: 'Killing Them Softly (2012)',
 65759: 'Happy Feet Two (2011)',
 72190: 'World War Z (2013)',
 76203: '12 Years a Slave (2013)',
 109091: 'The Counselor (2013)',
 228150: 'Fury (2014)',
 314385: 'By the Sea (2015)',
 318846: 'The Big Short (2015)',
 369885: 'Allied (2016)',
 383498: 'Deadpool 2 (2018)',
 419704: 'Ad Astra (2019)',
 466272: 'Once Upon a Time... in Hollywood (2019)',
 567604: 'Once Upon a Deadpool (2018)',
 615777: 'Babylon (2022)',
 639720: 'IF (2024)',
 718930: 'Bullet Train (2022)',
 752623: 'The Lost City (2022)',
 911430: 'F1 (2025)'}

In [10]:
movies[movies['actors'].map(lambda x: '287' in x)]

,movie_id,original_title,actors,year,revenue,adjusted_revenue
19,63,Twelve Monkeys,"287,62,290",1995,168841459.0,3.520422e+08
43,107,Snatch,"287,1121,976",2000,83557872.0,1.548928e+08
62,161,Ocean's Eleven,"19492,1204,1896,287,1461,1892,1893,1271,1897,1...",2001,450717150.0,8.143304e+08
64,163,Ocean's Twelve,"1204,1896,287,1461,62,1892,1922,3926,1925,1893...",2004,362744280.0,6.200282e+08
101,227,The Outsiders,"500,2963,2882,723,2876,2879,2880",1983,33697647.0,1.135439e+08
...,...,...,...,...,...,...
16452,1556422,Finding the Burn,"3910,287,1461,3063,6949,28633",2008,0.0,0.000000e+00
16453,1556433,DC Insiders Run Amuck,"3910,287,1461,3063",2008,0.0,0.000000e+00
16531,1595366,Behind the Scenes of 'Austin Powers: The Spy W...,"12073,13922,2879",1999,0.0,0.000000e+00
16586,1620445,On Location in Tulsa: The Making of 'Rumble Fish',"2963,2882,2295,2975,2778,2876",2005,0.0,0.000000e+00
16612,1629246,Most Outrageous Celebrity Splits,"11701,287",2024,0.0,0.000000e+00