In [1]:
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import requests

TMDB_API_KEY = "cc0093b5ad09a876190e097a1c2c8e65"
base_url = "https://api.themoviedb.org/3"

OUTPUT_DIR = ".."

# Make core.game_logic importable (same trick streamlit/app.py uses: put the
# streamlit/ directory itself on sys.path so `core` resolves as a top-level
# package). game_logic.py has no streamlit import, so this works standalone.
sys.path.append("../../streamlit")
from core.game_logic import build_and_save

In [3]:
"""Shared GET helper with retry + exponential backoff.

Retries on network errors and on HTTP 429 (rate limited), honoring TMDB's
Retry-After header when present. All API calls in this notebook go through
this so a burst of 429s during the threaded movie/detail fetches degrades
into a slowdown instead of silently dropped/failed requests.
"""

def request_with_retry(url, params, max_retries=5, backoff_base=1.0, timeout=10):
    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params, timeout=timeout)
        except requests.exceptions.RequestException:
            if attempt == max_retries - 1:
                raise
            time.sleep(backoff_base * (2 ** attempt))
            continue

        if response.status_code == 429:
            retry_after = response.headers.get('Retry-After')
            wait = float(retry_after) if retry_after else backoff_base * (2 ** attempt)
            print(f"Rate limited by TMDB, waiting {wait:.1f}s (attempt {attempt + 1}/{max_retries})")
            time.sleep(wait)
            continue

        response.raise_for_status()
        return response

    raise requests.exceptions.RequestException(f"Exceeded {max_retries} retries for {url}")

In [4]:
"""API call to retrieve the top N actors directly from TMDB's /person/popular

endpoint. Results are sorted by TMDB's popularity score; only people whose
known_for_department is "Acting" and who have at least one English-language
credit are kept, matching the same filter used for the existing dataset.
"""

def get_top_actors(limit=5000):
    actors = []
    page = 1

    while len(actors) < limit:
        try:
            response = request_with_retry(f"{base_url}/person/popular", params={
                'api_key': TMDB_API_KEY,
                'page': page
            })
            response = response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error: {e}")
            break

        results = response.get('results', [])
        if not results:
            break

        for person in results:
            is_english = any(item.get('original_language') == "en" for item in person.get('known_for', []))
            is_actor = person.get('known_for_department') == "Acting"

            if is_english and is_actor:
                actors.append({
                    'name': person['name'],
                    'tmdb_id': person['id']
                })

            if len(actors) >= limit:
                break

        print(f"Collected: {len(actors)} actors (Page {page})", end='\r')
        page += 1
        time.sleep(0.1)

    return pd.DataFrame(actors)


actor_list = get_top_actors(limit=5000)
actor_list

                     name  tmdb_id
0             Julia Doyle  2676077
1             Tom Holland  1136406
2              Matt Damon     1892
3     Alessandra Ambrosio   207606
4           Jason Statham      976
...                   ...      ...
4995      Péter Jankovics  1675710
4996        Jessica Szohr   130782
4997              Li Keyi  5698791
4998        George Cheung    16580
4999  Karissa Lee Staples  1254411

[5000 rows x 2 columns]

In [5]:
"""Single API call to retrieve the list of movies an actor is in."""

def get_movies(person_id):
    url = f"{base_url}/person/{person_id}/movie_credits"

    try:
        response = request_with_retry(url, params={
            'api_key': TMDB_API_KEY
        })
        response = response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        return None

    cast_list = pd.DataFrame(response['cast'])
    columns = ['id', 'original_language', 'original_title']
    cast_list = cast_list[columns].rename(columns={'id': 'movie_id'})

    return cast_list

In [6]:
"""Executes get_movies() for the full list of actors.

max_workers is kept modest (rather than firing hundreds of requests at once)
so the pool of concurrent requests stays reasonable; request_with_retry
handles any 429s that still slip through.
"""

def get_all_movies(actor_ids, max_workers=8):
    full_list = []
    total = len(actor_ids)
    completed = 0

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(get_movies, actor_id): actor_id for actor_id in actor_ids}

        for future in as_completed(futures):
            actor_id = futures[future]
            completed += 1

            try:
                result = future.result()
                if result is not None and not result.empty:
                    result['actor_id'] = actor_id
                    full_list.append(result)
                    print(f"[{completed}/{total}] Actor {actor_id} - {len(result)} movies found")
                else:
                    print(f"[{completed}/{total}] Actor {actor_id} - no results")

            except Exception as e:
                print(f"Actor ID: {actor_id} encountered an error: {e}")

    full_df = pd.concat(full_list, ignore_index=True)
    return full_df


expanded_movie_list = get_all_movies(actor_list['tmdb_id'], max_workers=8)

[1/5000] Actor 2638587 - 11 movies found
[2/5000] Actor 976 - 69 movies found
[3/5000] Actor 2676077 - 2 movies found
[4/5000] Actor 1892 - 128 movies found
[5/5000] Actor 207606 - 10 movies found
[6/5000] Actor 947296 - 22 movies found
[7/5000] Actor 31 - 181 movies found
[8/5000] Actor 1136406 - 40 movies found
[9/5000] Actor 2894471 - 3 movies found
[10/5000] Actor 1397778 - 42 movies found
[11/5000] Actor 1245 - 100 movies found
[12/5000] Actor 5081 - 61 movies found
[13/5000] Actor 1493434 - 7 movies found
[14/5000] Actor 505710 - 36 movies found
[15/5000] Actor 1813 - 84 movies found
[16/5000] Actor 64439 - 62 movies found
[17/5000] Actor 11288 - 54 movies found
[18/5000] Actor 19498 - 52 movies found
[19/5000] Actor 1721740 - 16 movies found
[20/5000] Actor 115440 - 55 movies found
[21/5000] Actor 287 - 112 movies found
[22/5000] Actor 126932 - 55 movies found
[23/5000] Actor 18897 - 204 movies found
[24/5000] Actor 64295 - 36 movies found
[25/5000] Actor 500 - 94 movies found
[26/5000] Actor 54882 - 35 movies found
[27/5000] Actor 6885 - 77 movies found
[28/5000] Actor 1425934 - 22 movies found
Actor ID: 3444960 encountered an error: "None of [Index(['id', 'original_language', 'original_title'], dtype='object')] are in the [columns]"
[30/5000] Actor 974169 - 37 movies found
[31/5000] Actor 1172108 - 46 movies found
[32/5000] Actor 27578 - 47 movies found
[33/5000] Actor 234352 - 37 movies found
[34/5000] Actor 2948491 - 2 movies found
[35/5000] Actor 1253360 - 49 movies found
[36/5000] Actor 30614 - 48 movies found
[37/5000] Actor 4783 - 146 movies found
[38/5000] Actor 2478377 - 1 movies found
[39/5000] Actor 3455931 - 6 movies found
[40/5000] Actor 1267329 - 40 movies found
[41/5000] Actor 1278487 - 27 movies found
[42/5000] Actor 1222298 - 15 movies found
[43/5000] Actor 4762373 - 3 movies found
[44/5000] Actor 109513 - 40 movies found
[45/5000] Actor 1356210 - 16 movies found
[46/5000] Actor 2963 - 155 movies found
[47/5000] Actor 1190668 - 39 movies found
[48/5000] Actor 933238 - 30 movies found
[49/5000] Actor 1212 - 31 movies found
[50/5000] Actor 21911 - 104 movies found
[51/5000] Actor 3223 - 129 movies found
[52/5000] Actor 12835 - 63 movies found
[53/5000] Actor 5723 - 151 movies found
[54/5000] Actor 73968 - 38 movies found
[55/5000] Actor 6384 - 146 movies found
[56/5000] Actor 2046128 - 10 movies found
[57/5000] Actor 85 - 155 movies found
[58/5000] Actor 6193 - 89 movies found
[59/5000] Actor 933271 - 16 movies found
[60/5000] Actor 206 - 100 movies found
[61/5000] Actor 6161 - 58 movies found
[62/5000] Actor 2718335 - 2 movies found
[63/5000] Actor 64 - 116 movies found
[64/5000] Actor 5292 - 88 movies found
[65/5000] Actor 56446 - 369 movies found
[66/5000] Actor 1700947 - 11 movies found
[67/5000] Actor 16483 - 153 movies found
[68/5000] Actor 2404163 - 1 movies found
[69/5000] Actor 1590797 - 16 movies found
[70/5000] Actor 2573266 - 4 movies found
[71/5000] Actor 72129 - 50 movies found
[72/5000] Actor 11701 - 81 movies found
[73/5000] Actor 62 - 165 movies found
[74/5000] Actor 55256 - 26 movies found
[75/5000] Actor 1284159 - 29 movies found
[76/5000] Actor 18999 - 153 movies found
[77/5000] Actor 2227 - 115 movies found
[78/5000] Actor 18918 - 285 movies found
[79/5000] Actor 73457 - 64 movies found
[80/5000] Actor 10859 - 94 movies found
[81/5000] Actor 2206 - 51 movies found
[82/5000] Actor 54693 - 52 movies found
[83/5000] Actor 2231 - 256 movies found
[84/5000] Actor 224513 - 37 movies found
[85/5000] Actor 38666 - 28 movies found
[86/5000] Actor 49624 - 16 movies found
[87/5000] Actor 10882 - 53 movies found
[88/5000] Actor 117642 - 56 movies found
[89/5000] Actor 1562430 - 7 movies found
[90/5000] Actor 1932318 - 5 movies found
[91/5000] Actor 192 - 203 movies found
[92/5000] Actor 17521 - 39 movies found
[93/5000] Actor 94797 - 19 movies found
[94/5000] Actor 3896 - 190 movies found
[95/5000] Actor 1337805 - 1 movies found
[96/5000] Actor 27163 - 113 movies found
[97/5000] Actor 70851 - 164 movies found
Actor ID: 2715667 encountered an error: "None of [Index(['id', 'original_language', 'original_title'], dtype='object')] are in the [columns]"
[99/5000] Actor 2604515 - 9 movies found
[100/5000] Actor 19537 - 42 movies found
[101/5000] Actor 88029 - 47 movies found
[102/5000] Actor 17605 - 95 movies found
[103/5000] Actor 17419 - 105 movies found
[104/5000] Actor 1836114 - 10 movies found
[105/5000] Actor 38673 - 69 movies found
[106/5000] Actor 211596 - 13 movies found
[107/5000] Actor 205 - 87 movies found
[108/5000] Actor 205486 - 9 movies found
[109/5000] Actor 74568 - 62 movies found
[110/5000] Actor 16828 - 70 movies found
[111/5000] Actor 131 - 75 movies found
[112/5000] Actor 56365 - 24 movies found
[113/5000] Actor 56734 - 73 movies found
[114/5000] Actor 17303 - 33 movies found
[115/5000] Actor 2438247 - 1 movies found
[116/5000] Actor 27972 - 65 movies found
[117/5000] Actor 1373737 - 35 movies found
[118/5000] Actor 10297 - 95 movies found
[119/5000] Actor 5293 - 221 movies found
[120/5000] Actor 28782 - 102 movies found
[121/5000] Actor 880 - 105 movies found
[122/5000] Actor 501 - 60 movies found
[123/5000] Actor 26723 - 40 movies found
[124/5000] Actor 17346 - 42 movies found
[125/5000] Actor 10990 - 31 movies found
[126/5000] Actor 71580 - 105 movies found
[127/5000] Actor 380 - 224 movies found
[128/5000] Actor 18324 - 78 movies found
[129/5000] Actor 524 - 73 movies found
[130/5000] Actor 56024 - 80 movies found
[131/5000] Actor 4494 - 31 movies found
[132/5000] Actor 1137824 - 23 movies found
[133/5000] Actor 1003162 - 34 movies found
[134/5000] Actor 17286 - 67 movies found
[135/5000] Actor 1222992 - 28 movies found
[136/5000] Actor 53650 - 83 movies found
[137/5000] Actor 190 - 178 movies found
[138/5000] Actor 2524 - 62 movies found
[139/5000] Actor 1372 - 44 movies found
[140/5000] Actor 2037 - 70 movies found
[141/5000] Actor 1224431 - 7 movies found
[142/5000] Actor 2461 - 114 movies found
[143/5000] Actor 1771746 - 15 movies found
[144/5000] Actor 589162 - 20 movies found
[145/5000] Actor 2888 - 112 movies found
[146/5000] Actor 2034418 - 25 movies found
[147/5000] Actor 10205 - 140 movies found
[148/5000] Actor 1372369 - 31 movies found
[149/5000] Actor 10980 - 56 movies found
[150/5000] Actor 164945 - 31 movies found
[151/5000] Actor 935 - 61 movies found
[152/5000] Actor 6968 - 104 movies found
[153/5000] Actor 18050 - 65 movies found
[154/5000] Actor 16851 - 92 movies found
[155/5000] Actor 37625 - 45 movies found
[156/5000] Actor 71070 - 60 movies found
[157/5000] Actor 204 - 79 movies found
[158/5000] Actor 6574 - 183 movies found
[159/5000] Actor 1496341 - 21 movies found
[160/5000] Actor 8293 - 115 movies found
[161/5000] Actor 20212 - 124 movies found
[162/5000] Actor 47296 - 55 movies found
[163/5000] Actor 1639 - 71 movies found
[164/5000] Actor 1158 - 122 movies found
[165/5000] Actor 5123305 - 1 movies found
[166/5000] Actor 1100 - 170 movies found
[167/5000] Actor 1223786 - 32 movies found
[168/5000] Actor 9273 - 63 movies found
[169/5000] Actor 3810 - 82 movies found
[170/5000] Actor 3894 - 79 movies found
[171/5000] Actor 13240 - 81 movies found
[172/5000] Actor 55638 - 125 movies found
[173/5000] Actor 1152083 - 28 movies found
[174/5000] Actor 51797 - 54 movies found
[175/5000] Actor 18082 - 51 movies found
[176/5000] Actor 63 - 77 movies found
[177/5000] Actor 9827 - 72 movies found
[178/5000] Actor 25072 - 82 movies found
[179/5000] Actor 48 - 129 movies found
[180/5000] Actor 1231 - 118 movies found
[181/5000] Actor 11008 - 52 movies found
[182/5000] Actor 10912 - 32 movies found
[183/5000] Actor 116 - 68 movies found
[184/5000] Actor 587020 - 24 movies found
[185/5000] Actor 2426268 - 2 movies found
[186/5000] Actor 18285 - 45 movies found
[187/5000] Actor 679 - 47 movies found
[188/5000] Actor 17604 - 60 movies found
[189/5000] Actor 1772 - 47 movies found
[190/5000] Actor 3839205 - 5 movies found
[191/5000] Actor 65731 - 66 movies found
[192/5000] Actor 9562 - 53 movies found
[193/5000] Actor 887 - 95 movies found
[194/5000] Actor 109 - 116 movies found
[195/5000] Actor 3118207 - 7 movies found
[196/5000] Actor 4724 - 127 movies found
[197/5000] Actor 6886 - 76 movies found
[198/5000] Actor 4173 - 170 movies found
[199/5000] Actor 1683343 - 17 movies found
[200/5000] Actor 11006 - 81 movies found
[201/5000] Actor 17276 - 79 movies found
[202/5000] Actor 3897 - 43 movies found
[203/5000] Actor 51329 - 74 movies found
[204/5000] Actor 8944 - 115 movies found
[205/5000] Actor 8784 - 86 movies found
[206/5000] Actor 95706 - 13 movies found
[207/5000] Actor 1785654 - 12 movies found
[208/5000] Actor 1336 - 65 movies found
[209/5000] Actor 19034 - 24 movies found
[210/5000] Actor 8891 - 139 movies found
[211/5000] Actor 955 - 98 movies found
[212/5000] Actor 17697 - 51 movies found
[213/5000] Actor 25654 - 39 movies found
[214/5000] Actor 77700 - 23 movies found
[215/5000] Actor 819 - 78 movies found
[216/5000] Actor 120923 - 56 movies found
[217/5000] Actor 20089 - 78 movies found
[218/5000] Actor 91671 - 62 movies found
[219/5000] Actor 550843 - 37 movies found
[220/5000] Actor 3416 - 73 movies found
[221/5000] Actor 96625 - 23 movies found
[222/5000] Actor 2121005 - 11 movies found
[223/5000] Actor 53714 - 40 movies found
[224/5000] Actor 2203 - 85 movies found
[225/5000] Actor 27740 - 73 movies found
[226/5000] Actor 16644 - 128 movies found
[227/5000] Actor 1269 - 110 movies found
[228/5000] Actor 418 - 128 movies found
[229/5000] Actor 18277 - 65 movies found
[230/5000] Actor 1206334 - 35 movies found
[231/5000] Actor 23532 - 77 movies found
[232/5000] Actor 73421 - 68 movies found
[233/5000] Actor 25702 - 38 movies found
[234/5000] Actor 27811 - 72 movies found
[235/5000] Actor 72466 - 74 movies found
[236/5000] Actor 1234713 - 2 movies found
[237/5000] Actor 59315 - 60 movies found
[238/5000] Actor 80860 - 28 movies found
[239/5000] Actor 1467219 - 16 movies found
[240/5000] Actor 5469 - 110 movies found
[241/5000] Actor 112 - 128 movies found
[242/5000] Actor 25663 - 49 movies found
[243/5000] Actor 83002 - 77 movies found
[244/5000] Actor 2520942 - 7 movies found
[245/5000] Actor 3417134 - 6 movies found
[246/5000] Actor 5472 - 102 movies found
[247/5000] Actor 122851 - 44 movies found
[248/5000] Actor 140 - 86 movies found
[249/5000] Actor 81133 - 30 movies found
[250/5000] Actor 10696 - 71 movies found
[251/5000] Actor 228 - 119 movies found
[252/5000] Actor 776 - 100 movies found
[253/5000] Actor 8691 - 81 movies found
[254/5000] Actor 21089 - 119 movies found
[255/5000] Actor 135651 - 43 movies found
[256/5000] Actor 3895 - 203 movies found
[257/5000] Actor 6614 - 42 movies found
[258/5000] Actor 57755 - 152 movies found
[259/5000] Actor 1003 - 123 movies found
[260/5000] Actor 1337 - 109 movies found
[261/5000] Actor 3 - 152 movies found
[262/5000] Actor 9195 - 94 movies found
[263/5000] Actor 2440 - 139 movies found
[264/5000] Actor 78110 - 84 movies found
[265/5000] Actor 11023 - 48 movies found
[266/5000] Actor 10431 - 99 movies found
[267/5000] Actor 1631759 - 62 movies found
[268/5000] Actor 17288 - 59 movies found
[269/5000] Actor 4174 - 47 movies found
[270/5000] Actor 17838 - 35 movies found
[271/5000] Actor 127558 - 57 movies found
[272/5000] Actor 62220 - 16 movies found
[273/5000] Actor 7056 - 108 movies found
[274/5000] Actor 94423 - 13 movies found
[275/5000] Actor 24045 - 85 movies found
[276/5000] Actor 60898 - 60 movies found
[277/5000] Actor 2157 - 202 movies found
[278/5000] Actor 1392137 - 35 movies found
[279/5000] Actor 27319 - 114 movies found
[280/5000] Actor 125025 - 50 movies found
[281/5000] Actor 103 - 91 movies found
[282/5000] Actor 3967 - 58 movies found
[283/5000] Actor 3293 - 61 movies found
[284/5000] Actor 7152 - 49 movies found
[285/5000] Actor 58115 - 31 movies found
[286/5000] Actor 5064 - 154 movies found
[287/5000] Actor 6194 - 40 movies found
[288/5000] Actor 37917 - 72 movies found
[289/5000] Actor 1972974 - 15 movies found
[290/5000] Actor 77948 - 65 movies found
[291/5000] Actor 15111 - 92 movies found
[292/5000] Actor 92614 - 21 movies found
[293/5000] Actor 237455 - 40 movies found
[294/5000] Actor 18973 - 56 movies found
[295/5000] Actor 11181 - 107 movies found
[296/5000] Actor 2372 - 207 movies found
[297/5000] Actor 1019 - 77 movies found
[298/5000] Actor 63585 - 67 movies found
[299/5000] Actor 36594 - 54 movies found
[300/5000] Actor 7499 - 64 movies found
[301/5000] Actor 91606 - 61 movies found
[302/5000] Actor 5887 - 31 movies found
[303/5000] Actor 21315 - 680 movies found
[304/5000] Actor 19292 - 128 movies found
[305/5000] Actor 4491 - 66 movies found
[306/5000] Actor 15277 - 74 movies found
Actor ID: 2452208 encountered an error: "None of [Index(['id', 'original_language', 'original_title'], dtype='object')] are in the [columns]"
[308/5000] Actor 884 - 179 movies found
[309/5000] Actor 1038 - 100 movies found
[310/5000] Actor 3131 - 156 movies found
[311/5000] Actor 139 - 86 movies found
[312/5000] Actor 3128782 - 5 movies found
[313/5000] Actor 2264310 - 2 movies found
[314/5000] Actor 5530 - 64 movies found
[315/5000] Actor 543530 - 168 movies found
[316/5000] Actor 6856 - 99 movies found
[317/5000] Actor 58502 - 29 movies found
[318/5000] Actor 15555 - 39 movies found
[319/5000] Actor 783 - 87 movies found
[320/5000] Actor 1059597 - 33 movies found
[321/5000] Actor 569 - 120 movies found
[322/5000] Actor 1108907 - 26 movies found
[323/5000] Actor 212225 - 44 movies found
[324/5000] Actor 1223059 - 14 movies found
[325/5000] Actor 90633 - 34 movies found
[326/5000] Actor 77234 - 89 movies found
[327/5000] Actor 2340180 - 13 movies found
[328/5000] Actor 16431 - 81 movies found
[329/5000] Actor 137905 - 46 movies found
[330/5000] Actor 35029 - 51 movies found
[331/5000] Actor 4495 - 69 movies found
[332/5000] Actor 204747 - 9 movies found
[333/5000] Actor 22226 - 115 movies found
[334/5000] Actor 25246 - 215 movies found
[335/5000] Actor 39459 - 45 movies found
[336/5000] Actor 17051 - 167 movies found
[337/5000] Actor 206905 - 28 movies found
[338/5000] Actor 143346 - 59 movies found
[339/5000] Actor 59410 - 76 movies found
[340/5000] Actor 2283 - 131 movies found
[341/5000] Actor 4430 - 138 movies found
[342/5000] Actor 1461 - 116 movies found
[343/5000] Actor 84215 - 39 movies found
[344/5000] Actor 119592 - 73 movies found
[345/5000] Actor 39389 - 47 movies found
[346/5000] Actor 368 - 64 movies found
[347/5000] Actor 4808 - 140 movies found
[348/5000] Actor 29222 - 63 movies found
[349/5000] Actor 886 - 82 movies found
[350/5000] Actor 543505 - 41 movies found
[351/5000] Actor 226001 - 40 movies found
[352/5000] Actor 2578201 - 3 movies found
[353/5000] Actor 19274 - 107 movies found
[354/5000] Actor 22970 - 82 movies found
[355/5000] Actor 11355 - 122 movies found
[356/5000] Actor 1283 - 123 movies found
[357/5000] Actor 8167 - 38 movies found
[358/5000] Actor 71189 - 34 movies found
[359/5000] Actor 13548 - 50 movies found
[360/5000] Actor 20381 - 22 movies found
[361/5000] Actor 1502916 - 12 movies found
[362/5000] Actor 2219 - 49 movies found
[363/5000] Actor 1236264 - 19 movies found
[364/5000] Actor 38334 - 80 movies found
[365/5000] Actor 9824 - 68 movies found
[366/5000] Actor 504 - 100 movies found
[367/5000] Actor 51072 - 46 movies found
[368/5000] Actor 3490 - 87 movies found
[369/5000] Actor 7399 - 133 movies found
[370/5000] Actor 49735 - 84 movies found
[371/5000] Actor 59175 - 39 movies found
[372/5000] Actor 1925 - 111 movies found
[373/5000] Actor 41421 - 51 movies found
[374/5000] Actor 4292708 - 12 movies found
[375/5000] Actor 59192 - 54 movies found
[376/5000] Actor 11705 - 49 movies found
[377/5000] Actor 130640 - 38 movies found
[378/5000] Actor 14405 - 54 movies found
[379/5000] Actor 6195 - 49 movies found
[380/5000] Actor 93491 - 30 movies found
[381/5000] Actor 1446006 - 3 movies found
[382/5000] Actor 88124 - 52 movies found
[383/5000] Actor 229932 - 72 movies found
[384/5000] Actor 989325 - 26 movies found
[385/5000] Actor 1173984 - 25 movies found
[386/5000] Actor 25837 - 26 movies found
[387/5000] Actor 60373 - 17 movies found
[388/5000] Actor 1227717 - 21 movies found
[389/5000] Actor 6941 - 79 movies found
[390/5000] Actor 543261 - 66 movies found
[391/5000] Actor 2882 - 79 movies found
[392/5000] Actor 1251069 - 31 movies found
[393/5000] Actor 1844511 - 5 movies found
[394/5000] Actor 2282 - 171 movies found
[395/5000] Actor 36662 - 39 movies found
[396/5000] Actor 150899 - 34 movies found
[397/5000] Actor 38405 - 58 movies found
[398/5000] Actor 69597 - 112 movies found
[399/5000] Actor 4391 - 120 movies found
[400/5000] Actor 4690 - 152 movies found
[401/5000] Actor 1271 - 112 movies found
[402/5000] Actor 18997 - 48 movies found
[403/5000] Actor 556356 - 40 movies found
[404/5000] Actor 2803710 - 16 movies found
[405/5000] Actor 115679 - 16 movies found
[406/5000] Actor 83271 - 49 movies found
[407/5000] Actor 114 - 68 movies found
[408/5000] Actor 23659 - 137 movies found
[409/5000] Actor 64436 - 85 movies found
[410/5000] Actor 1024395 - 77 movies found
[411/5000] Actor 2447707 - 2 movies found
[412/5000] Actor 1442069 - 31 movies found
[413/5000] Actor 1047649 - 29 movies found
[414/5000] Actor 3061 - 125 movies found
[415/5000] Actor 15735 - 163 movies found
[416/5000] Actor 55751 - 10 movies found
[417/5000] Actor 46364 - 94 movies found
[418/5000] Actor 1303037 - 27 movies found
[419/5000] Actor 40462 - 81 movies found
[420/5000] Actor 34486 - 52 movies found
[421/5000] Actor 289 - 31 movies found
[422/5000] Actor 4939 - 23 movies found
[423/5000] Actor 1160 - 80 movies found
[424/5000] Actor 74409 - 13 movies found
[425/5000] Actor 2982884 - 7 movies found
[426/5000] Actor 118545 - 43 movies found
[427/5000] Actor 1230 - 156 movies found
[428/5000] Actor 12214 - 62 movies found
[429/5000] Actor 86654 - 34 movies found
[430/5000] Actor 58058 - 196 movies found
[431/5000] Actor 990393 - 18 movies found
[432/5000] Actor 934 - 103 movies found
[433/5000] Actor 1538851 - 21 movies found
[434/5000] Actor 74949 - 60 movies found
[435/5000] Actor 517 - 144 movies found
[436/5000] Actor 49 - 57 movies found
[437/5000] Actor 16501 - 44 movies found
[438/5000] Actor 3188432 - 1 movies found
[439/5000] Actor 11108 - 101 movies found
[440/5000] Actor 4587 - 96 movies found
[441/5000] Actor 54421 - 39 movies found
[442/5000] Actor 1974046 - 18 movies found
[443/5000] Actor 6383 - 64 movies found
[444/5000] Actor 37632 - 31 movies found
[445/5000] Actor 19536 - 54 movies found
[446/5000] Actor 19961 - 37 movies found
[447/5000] Actor 78921 - 85 movies found
[448/5000] Actor 1213613 - 23 movies found
[449/5000] Actor 4088089 - 10 movies found
[450/5000] Actor 10730 - 89 movies found
[451/5000] Actor 21657 - 66 movies found
[452/5000] Actor 999449 - 32 movies found
[453/5000] Actor 1817 - 44 movies found
[454/5000] Actor 78080 - 33 movies found
[455/5000] Actor 8767 - 51 movies found
[456/5000] Actor 1205 - 93 movies found
[457/5000] Actor 110 - 85 movies found
[458/5000] Actor 1039011 - 26 movies found
[459/5000] Actor 1016168 - 40 movies found
[460/5000] Actor 1549008 - 26 movies found
[461/5000] Actor 281985 - 17 movies found
[462/5000] Actor 6944 - 98 movies found
[463/5000] Actor 1893 - 54 movies found
[464/5000] Actor 6807 - 117 movies found
[465/5000] Actor 3899 - 69 movies found
[466/5000] Actor 658 - 159 movies found
[467/5000] Actor 1640 - 159 movies found
[468/5000] Actor 9642 - 90 movies found
[469/5000] Actor 87722 - 49 movies found
[470/5000] Actor 2551735 - 2 movies found
[471/5000] Actor 1549005 - 18 movies found
[472/5000] Actor 56731 - 50 movies found
[473/5000] Actor 1098962 - 31 movies found
[474/5000] Actor 1981044 - 13 movies found
[475/5000] Actor 1695989 - 19 movies found
[476/5000] Actor 1327 - 169 movies found
[477/5000] Actor 16866 - 98 movies found
[478/5000] Actor 97906 - 84 movies found
[479/5000] Actor 1920 - 78 movies found
[480/5000] Actor 2713 - 68 movies found

In [7]:
movie_list = expanded_movie_list.groupby(['movie_id', 'original_language', 'original_title'])['actor_id']
movie_list = movie_list.apply(lambda x: ",".join(x.astype(str))).reset_index()
movie_list = movie_list.rename(columns={"actor_id": "actors"})
movie_list = movie_list[movie_list['actors'].str.contains(",")]
movie_list = movie_list[movie_list['original_language'] == "en"]
movie_list

,movie_id,original_language,original_title,actors
0,5,en,Four Rooms,"62,3131,3141,3129,3130,3136,3124,3128,3125,313..."
1,6,en,Judgment Night,"5724,12799,9777,10822,2880,11803"
2,11,en,Star Wars,"3,2,4,12248,15152,5,69249"
3,12,en,Finding Nemo,"5293,8783,19,17401,20,118,57675,18,7907,13,613..."
4,13,en,Forrest Gump,"31,6856,35,9640,32,34,33,36221,21457"
...,...,...,...,...
104007,1738103,en,Julie and the Phantoms,"1932318,121868"
104013,1738359,en,Labyrinth,"2478,327,21594,81295"
104015,1738399,en,Star Wars: Maul - Shadow Lord,"52583,352,1217648,98103"
104017,1738470,en,The Winds of Winter,"1223786,1001657"
104018,1738479,en,The Rains of Castamere,"1223786,20508,512991"

In [8]:
"""Single API call to get the remaining movie details needed."""

def get_details(movie_id):
    url = f"{base_url}/movie/{movie_id}"

    try:
        response = request_with_retry(url, params={
            'api_key': TMDB_API_KEY
        })
        response = response.json()

        return {
            "id": movie_id,
            "year": response.get("release_date", "")[:4],
            "revenue": response.get("revenue")
        }

    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")
        return {"id": None, "year": None, "revenue": None}

In [9]:
"""max_workers is kept modest here too, for the same reason as get_all_movies."""

def get_all_details(movie_ids, max_workers=10):
    full_data = []
    total = len(movie_ids)
    completed = 0

    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(get_details, movie_id): movie_id for movie_id in movie_ids}

        for future in as_completed(futures):
            completed += 1

            try:
                result = future.result()
                full_data.append(result)
            except Exception as e:
                print(f"Error: {e}")

            print(f"[{completed}/{total}]", end='\r')

    df = pd.DataFrame(full_data, columns=["id", "year", "revenue"])
    df = df.sort_values("id").reset_index(drop=True)

    return df


final_movie_details = get_all_details(movie_list["movie_id"], max_workers=10)

In [10]:
inflation_data = pd.read_excel("../BLS Inflation History.xlsx", header=11)
inflation_data['Annual'] = inflation_data['Annual'].fillna(inflation_data['Jan'])
inflation_data = inflation_data[['Year', 'Annual']]
cpi = pd.Series(inflation_data.set_index('Year')['Annual'])

def adjust_for_inflation(value, from_year, to_year=2026, cpi=cpi):
    if from_year == to_year:
        return value

    years = range(from_year + 1, to_year + 1)
    multiplier = 1
    for year in years:
        rate = cpi[year] / 100
        multiplier = multiplier * (1 + rate)

    return round(value * multiplier, 2)

c:\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [11]:
final_movie_list = movie_list.merge(final_movie_details, left_on='movie_id', right_on='id', how="left")
final_movie_list = final_movie_list.drop(columns=["original_language", "id"])
final_movie_list = final_movie_list[final_movie_list["year"] != ""]
final_movie_list = final_movie_list[final_movie_list["year"].isna() == False]
final_movie_list['year'] = final_movie_list['year'].astype(int)
final_movie_list = final_movie_list[final_movie_list['year'] >= 1958]
final_movie_list["adjusted_revenue"] = final_movie_list.apply(lambda row: adjust_for_inflation(row['revenue'], row['year']), axis=1)
final_movie_list

,movie_id,original_title,actors,year,revenue,adjusted_revenue
0,5,Four Rooms,"62,3131,3141,3129,3130,3136,3124,3128,3125,313...",1995,4257354,8.876780e+06
1,6,Judgment Night,"5724,12799,9777,10822,2880,11803",1993,12136938,2.679509e+07
2,11,Star Wars,"3,2,4,12248,15152,5,69249",1977,775398007,4.270401e+09
3,12,Finding Nemo,"5293,8783,19,17401,20,118,57675,18,7907,13,613...",2003,940335536,1.636219e+09
4,13,Forrest Gump,"31,6856,35,9640,32,34,33,36221,21457",1994,677387716,1.454756e+09
...,...,...,...,...,...,...
43506,1737513,Tiada Pengganti MV - Behind the Scenes,"10980,42160",2026,0,0.000000e+00
43508,1737768,Robot Chicken Adult Swim Special,"51798,80757",2026,0,0.000000e+00
43511,1737989,Bad Bunny's Super Bowl LX Halftime Show,"128057,2550161",2026,0,0.000000e+00
43514,1738085,TERM,"2,14329",2026,0,0.000000e+00
43516,1738359,Labyrinth,"2478,327,21594,81295",2025,0,0.000000e+00

In [12]:
final_movie_list.to_parquet(f"{OUTPUT_DIR}/final_movies.parquet")
actor_list.to_parquet(f"{OUTPUT_DIR}/actor_list.parquet")

In [ ]:
"""Build a difficulty-tiered game_data.pkl for each actor-pool size, via
core.game_logic.build_and_save(). Rereads actor_list.parquet from disk
(rather than reusing the in-memory actor_list variable from the cells above)
so this cell is self-contained and can be rerun on its own - after a kernel
restart, or to regenerate tiers - without redoing the API pulls above.

actor_list is already ordered by TMDB popularity (get_top_actors() appends
pages of /person/popular in the order returned), so actor_list.head(n) is
exactly the top n most popular actors.

build_and_save() prunes movies/actors that fall outside the given actor pool
on its own, so reusing the same final_movies.parquet for every tier and only
varying the actor list is enough to produce a correctly-connected sub-graph
per tier.
"""

actor_list = pd.read_parquet(f"{OUTPUT_DIR}/actor_list.parquet")

DIFFICULTY_TIERS = {
    'easy': 500,
    'medium': 1500,
    'hard': 5000,
}

for difficulty, actor_count in DIFFICULTY_TIERS.items():
    tier_actors_path = f"{OUTPUT_DIR}/_tmp_actor_list_{difficulty}.parquet"
    actor_list.head(actor_count).to_parquet(tier_actors_path)

    build_and_save(
        f"{OUTPUT_DIR}/final_movies.parquet",
        tier_actors_path,
        output_path=f"{OUTPUT_DIR}/game_data_{difficulty}.pkl",
    )

    os.remove(tier_actors_path)